services:

  web:
    container_name: web_app_container
    image: drorganvidez/uvlhub:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    expose:
      - "5000"
    environment:
      FLASK_ENV: development
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_TEST_DATABASE: ${MARIADB_TEST_DATABASE}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    depends_on:
      - db

  db:
    container_name: mariadb_container
    build:
      context: ./
      dockerfile: Dockerfile.mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: nginx_web_server
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx/nginx.dev.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_data:
