version: '3.8'

services:

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 80:5000
    environment:
      FLASK_ENV: development
    depends_on:
      - db
  
  flamapyapi:
    image: drorganvidez/flamapyapi:latest
    ports:
      - 5000:5000

  fm_characterization:
    image: drorganvidez/fm_characterization_api:latest
    ports:
      - 5001:5000

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
