services:

  web:
    container_name: web_app_container
    image: drorganvidez/uvlhub:latest
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_TEST_DATABASE: ${MARIADB_TEST_DATABASE}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    depends_on:
      - db
    restart: always

  db:
    container_name: mariadb_container
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: nginx_web_server
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./public:/var/www:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always

  watchtower:
    container_name: watchtower_container
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 120 web_app_container
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    volumes:
      - ./public:/var/www:rw
      - ./letsencrypt:/etc/letsencrypt

volumes:
  db_data:
