version: '3.8'

services:

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  flamapyapi:
    image: flamapy/flamapy-fm-dist:v1.5.3
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    expose:
      - 8000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    depends_on:
      - flamapyapi

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
