services:

  - type: pserv
    name: web-app
    plan: free
    dockerfilePath: ./docker/images/Dockerfile.render
    dockerCommand: ./docker/entrypoints/render_entrypoint.sh
    envVars:
      - key: FLASK_APP_NAME
        value: "UVLHUB.IO"
      - key: FLASK_ENV
        value: production
      - key: DOMAIN
        value: "render.com"
      - key: MARIADB_HOSTNAME
        value: db
      - key: MARIADB_PORT
        value: "3306"
      - key: MARIADB_DATABASE
        value: uvlhubdb
      - key: MARIADB_USER
        generateValue: true
      - key: MARIADB_PASSWORD
        generateValue: true
      - key: MARIADB_ROOT_PASSWORD
        generateValue: true
      - key: WORKING_DIR
        value: /app/
    runtime: docker

  - type: pserv
    name: db
    plan: free
    image:
      url: docker.io/mariadb:latest
    startCommand: "mysqld --default-authentication-plugin=mysql_native_password"
    envVars:
      - key: MARIADB_HOSTNAME
        value: db
      - key: MARIADB_PORT
        value: "3306"
      - key: MARIADB_DATABASE
        value: uvlhubdb
      - key: MARIADB_USER
        generateValue: true
      - key: MARIADB_PASSWORD
        generateValue: true
      - key: MARIADB_ROOT_PASSWORD
        generateValue: true
    runtime: docker

  - type: web
    name: nginx
    plan: free
    dockerfilePath: ./docker/images/Dockerfile.nginx
    startCommand: ""
    runtime: docker
    healthCheckPath: /
