services:
  web:
    container_name: web_app_container
    image: drorganvidez/uvlhub:dev
    env_file:
      - ../.env
    expose:
      - "5000"
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.dev
    volumes:
      - ./entrypoints/development_entrypoint.sh:/app/entrypoint.sh
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "sh", "-c", "sh /app/entrypoint.sh" ]
    networks:
      - uvlhub_network

  db:
    container_name: mariadb_container
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - uvlhub_network

  nginx:
    container_name: nginx_web_server_container
    image: nginx:latest
    volumes:
      - type: bind
        source: nginx/nginx.dev.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - uvlhub_network

volumes:
  db_data:

networks:
  uvlhub_network:
