services:

  web:
    container_name: web_app_container
    image: drorganvidez/uvlhub:latest
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.prod
    restart: always
    volumes:
      - ../:/app
    command: [ "sh", "-c", "sh /app/docker/entrypoints/production_entrypoint.sh:" ]

  db:
    container_name: mariadb_container
    env_file:
      - ../.env
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: nginx_web_server_container
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

  deploy:
    container_name: deploy_manager_container
    build:
      context: ../
      dockerfile: Dockerfile.webhook
    volumes:
      - ../:/app
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../.env
    depends_on:
      - web
      - db
    restart: always

volumes:
  db_data: