name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: fmlibrootpass
          MYSQL_DATABASE: fmlibdb
          MYSQL_USER: fmlibuser
          MYSQL_PASSWORD: fmlibpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        export MYSQL_HOSTNAME=127.0.0.1
        export MYSQL_PORT=3306
        export MYSQL_DATABASE=fmlibdb
        export MYSQL_USER=fmlibuser
        export MYSQL_PASSWORD=fmlibpass
        pytest app/tests/units.py
