name: Pytest Testing Suite

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - review_requested
      - synchronize
  push:
    branches:
      - main
  workflow_call:

jobs:
  units:
    name: Unitary Testing
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: fmlibdb
          MYSQL_USER: fmlibuser
          MYSQL_PASSWORD: fmlibpass
          MYSQL_ROOT_PASSWORD: fmlibrootpass
        ports:
          - 3306:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Copy .env.example to .env
        run: cp .env.example .env
      - name: Prepare wait-for-it.sh
        run: |
          curl -sSLO https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
      - name: Get MySQL container IP
        run: |
          CONTAINER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql)
          echo "MySQL container IP: $CONTAINER_IP"
      - name: Wait for MySQL to be ready
        run: |
          CONTAINER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql)
          ./wait-for-it.sh $CONTAINER_IP:3306 --timeout=0 -- echo "MySQL is ready!"
      - name: Run unit tests
        run: pytest ./tests/units.py
